language: java
jdk: oraclejdk8

dist: xenial

addons:
  firefox: latest

# disable default mvn install
install: true

notifications:
  slack: qaengineering:eTRqy0JhQOUtKHNO8mKLc8NC

env:
  global:
    # - CAPTURE_URL="https://localhost:5000" # disabled until new instance is available
    - SUT_NAME="frameworkium"
    - SUT_VERSION=$TRAVIS_BRANCH
    - THREAD_COUNT=2
    - SELENIUM_MAJ_VER=3.5
    - SELENIUM_VER=${SELENIUM_MAJ_VER}.3
    - SELENIUM_JAR=selenium-server-standalone-${SELENIUM_VER}.jar
    - GECKO_VER=0.19.1
    - CHROME_DRIVER_VER=2.33

# setup X to allow non-headless browsers to run
before_script:
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -q

  # Download and setup Grid hub
  - wget https://selenium-release.storage.googleapis.com/$SELENIUM_MAJ_VER/selenium-server-standalone-$SELENIUM_VER.jar
  - java -jar selenium-server-standalone-$SELENIUM_VER.jar -role hub > /dev/null 2>&1 &

  # Download and setup geckodriver grid node
  - wget https://github.com/mozilla/geckodriver/releases/download/v${GECKO_VER}/geckodriver-v${GECKO_VER}-linux64.tar.gz
  - tar -xzf geckodriver-v${GECKO_VER}-linux64.tar.gz --directory /tmp
  - java -Dwebdriver.gecko.driver=/tmp/geckodriver -jar selenium-server-standalone-${SELENIUM_VER}.jar -role node -hub http://localhost:4444/grid/register -browser browserName=firefox,maxInstances=${THREAD_COUNT} -maxSession ${THREAD_COUNT} -port 5555 > /dev/null 2>&1 &

  # Run TheInternetExampleTests on Firefox off the grid
  - mvn verify -B -Dthreads=$THREAD_COUNT -Dbrowser=firefox -Dit.test=TheInternetExampleTests -Dwebdriver.gecko.driver=/tmp/geckodriver 2> /dev/null

  # Run all tests on Firefox on the grid via gecko
  - mvn verify -B -Dthreads=$THREAD_COUNT -Dconfig=FirefoxGrid.yaml # -DcaptureURL=$CAPTURE_URL -DsutName="$SUT_NAME" -DsutVersion="$SUT_VERSION"

  # Run TEST-1 and log to Jira
  - mvn verify -B -Dthreads=$THREAD_COUNT -Dconfig=FirefoxGrid.yaml -DjiraURL="http://52.29.130.45:8080" -DjqlQuery="issueKey=TEST-1" -DresultVersion="BUILD TEST VERSION" -DzapiCycleRegex="Test Cycle" -DjiraUsername=frameworkium -DjiraPassword=frameworkium

  # Run on sauce - disabled until we have a sauce account to use
  # - mvn verify -Dsauce=true -Dplatform=ios -Dbrowser=safari -DplatformVersion=8.0 -Ddevice=iPad -DcaptureURL=$CAPTURE_URL -DsutName="$SUT_NAME" -DsutVersion="$SUT_VERSION"

  # generate allure report
  - mvn site -B -q
