# Setup
title:        Frameworkium
tagline:      "A quick-start automation project for web, app, & api testing"
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#Others
# markdown: kramdown

highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge